  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Analyze Diversity in Bacterial Communities\n",
    "\n",
    "Let's calculate and analyze the diversity of the bacterial communities, similar to what we did with MetaPhlAn data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Calculate alpha diversity metrics for the bacterial data\n",
    "def calculate_alpha_diversity(abundance_df, metrics=['shannon', 'simpson', 'observed_otus']):\n",
    "    \"\"\"\n",
    "    Calculate alpha diversity metrics for all samples in the abundance table.\n",
    "    \n",
    "    Parameters:\n",
    "    -----------\n",
    "    abundance_df : pandas.DataFrame\n",
    "        Species abundance DataFrame with species as index, samples as columns\n",
    "    metrics : list\n",
    "        List of metrics to calculate ('shannon', 'simpson', 'observed_otus')\n",
    "        \n",
    "    Returns:\n",
    "    --------\n",
    "    pandas.DataFrame\n",
    "        DataFrame with samples as index and diversity metrics as columns\n",
    "    \"\"\"\n",
    "    from scipy.stats import entropy\n",
    "    import numpy as np\n",
    "    \n",
    "    # Initialize results DataFrame\n",
    "    results = pd.DataFrame(index=abundance_df.columns)\n",
    "    \n",
    "    for sample_id in abundance_df.columns:\n",
    "        # Get abundances for this sample\n",
    "        abundances = abundance_df[sample_id].values\n",
    "        \n",
    "        # Normalize to relative abundance\n",
    "        total = abundances.sum()\n",
    "        if total > 0:\n",
    "            rel_abundances = abundances / total\n",
    "        else:\n",
    "            rel_abundances = abundances\n",
    "        \n",
    "        # Count observed species (non-zero abundance)\n",
    "        observed = (abundances > 0).sum()\n",
    "        \n",
    "        # Calculate Shannon diversity\n",
    "        shannon = entropy(rel_abundances, base=2)\n",
    "        \n",
    "        # Calculate Simpson diversity (1 - D)\n",
    "        simpson = 1 - np.sum(rel_abundances**2)\n",
    "        \n",
    "        # Store results\n",
    "        if 'shannon' in metrics:\n",
    "            results.loc[sample_id, 'Shannon'] = shannon\n",
    "        if 'simpson' in metrics:\n",
    "            results.loc[sample_id, 'Simpson'] = simpson\n",
    "        if 'observed_otus' in metrics:\n",
    "            results.loc[sample_id, 'Observed'] = observed\n",
    "    \n",
    "    return results\n",
    "\n",
    "# Calculate alpha diversity if bacterial data is available\n",
    "if bacteria_file.exists():\n",
    "    bacteria_df = pd.read_csv(bacteria_file, index_col=0)\n",
    "    \n",
    "    # Calculate alpha diversity\n",
    "    alpha_diversity = calculate_alpha_diversity(bacteria_df)\n",
    "    print(\"Alpha diversity metrics for bacterial communities:\")\n",
    "    display(alpha_diversity.describe())\n",
    "    \n",
    "    # Load metadata for comparison\n",
    "    metadata_file = project_root / 'metadata.csv'\n",
    "    if metadata_file.exists():\n",
    "        metadata_df = pd.read_csv(metadata_file)\n",
    "        metadata_df.set_index('SampleID', inplace=True)\n",
    "        \n",
    "        # Merge alpha diversity with metadata\n",
    "        common_samples = list(set(alpha_diversity.index).intersection(set(metadata_df.index)))\n",
    "        if common_samples:\n",
    "            alpha_meta = alpha_diversity.loc[common_samples].copy()\n",
    "            for col in ['Timing', 'Symptoms', 'Severity']:\n",
    "                if col in metadata_df.columns:\n",
    "                    alpha_meta[col] = metadata_df.loc[common_samples, col].values\n",
    "            \n",
    "            # Create boxplots by group\n",
    "            for group_var in ['Timing', 'Symptoms', 'Severity']:\n",
    "                if group_var in alpha_meta.columns:\n",
    "                    fig, axes = plt.subplots(1, 3, figsize=(15, 6))\n",
    "                    \n",
    "                    # Shannon diversity\n",
    "                    sns.boxplot(x=group_var, y='Shannon', data=alpha_meta, ax=axes[0])\n",
    "                    axes[0].set_title(f'Shannon Diversity by {group_var}')\n",
    "                    \n",
    "                    # Simpson diversity\n",
    "                    sns.boxplot(x=group_var, y='Simpson', data=alpha_meta, ax=axes[1])\n",
    "                    axes[1].set_title(f'Simpson Diversity by {group_var}')\n",
    "                    \n",
    "                    # Observed species\n",
    "                    sns.boxplot(x=group_var, y='Observed', data=alpha_meta, ax=axes[2])\n",
    "                    axes[2].set_title(f'Observed Species by {group_var}')\n",
    "                    \n",
    "                    plt.tight_layout()\n",
    "                    plt.show()\n",
    "        else:\n",
    "            print(\"No common samples between alpha diversity and metadata\")\n",
    "    else:\n",
    "        print(\"Metadata file not found\")\n",
    "else:\n",
    "    print(\"Bacterial abundance file not found\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Compare Sylph with MetaPhlAn\n",
    "\n",
    "Let's compare the results from Sylph with the MetaPhlAn results."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Save the comparison script to a file if it doesn't exist yet\n",
    "if not comparison_script.exists():\n",
    "    # Copy the script content here\n",
    "    script_content = \"\"\"#!/usr/bin/env python3\n",
    "\"\"\"Compare results from Sylph and MetaPhlAn microbiome profiling.\"\"\"\n",
    "# ... (full script content from previously created artifact)\n",
    "\"\"\"\n",
    "    \n",
    "    with open(comparison_script, 'w') as f:\n",
    "        f.write(script_content)\n",
    "    \n",
    "    # Make it executable\n",
    "    os.chmod(comparison_script, 0o755)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Run the comparison script\n",
    "cmd = [\n",
    "    'python', str(comparison_script),\n",
    "    '--sylph-dir', str(processed_data_dir),\n",
    "    '--metaphlan-dir', str(processed_data_dir),\n",
    "    '--output-dir', str(comparison_dir),\n",
    "    '--metadata', str(project_root / 'metadata.csv')\n",
    "]\n",
    "\n",
    "# Execute the command and capture output\n",
    "process = subprocess.run(cmd, capture_output=True, text=True)\n",
    "\n",
    "# Print the output\n",
    "print(process.stdout)\n",
    "if process.stderr:\n",
    "    print(\"Errors:\")\n",
    "    print(process.stderr)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Examine the comparison results\n",
    "\n",
    "Now let's look at the comparison results between Sylph and MetaPhlAn."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Display the comparison results text file\n",
    "concordance_file = comparison_dir / 'method_concordance.txt'\n",
    "if concordance_file.exists():\n",
    "    with open(concordance_file, 'r') as f:\n",
    "        concordance_text = f.read()\n",
    "    print(concordance_text)\n",
    "else:\n",
    "    print(\"Concordance file not found\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Display the taxa correlation results\n",
    "correlation_file = comparison_dir / 'taxa_correlations.csv'\n",
    "if correlation_file.exists():\n",
    "    correlation_df = pd.read_csv(correlation_file)\n",
    "    print(\"Taxa correlations between Sylph and MetaPhlAn:\")\n",
    "    display(correlation_df.sort_values('spearman_r', ascending=False).head(10))\n",
    "else:\n",
    "    print(\"Correlation file not found\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Display comparison plots\n",
    "comparison_figures = comparison_dir / 'figures'\n",
    "if comparison_figures.exists():\n",
    "    # Find all PNG files in the figures directory\n",
    "    png_files = list(comparison_figures.glob('*.png'))\n",
    "    \n",
    "    if png_files:\n",
    "        for png_file in png_files:\n",
    "            # Display the image\n",
    "            plt.figure(figsize=(12, 10))\n",
    "            img = plt.imread(png_file)\n",
    "            plt.imshow(img)\n",
    "            plt.axis('off')\n",
    "            plt.title(png_file.stem)\n",
    "            plt.show()\n",
    "    else:\n",
    "        print(\"No PNG files found in the figures directory\")\n",
    "else:\n",
    "    print(\"Figures directory not found\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Analyze Viral and Fungal Results\n",
    "\n",
    "Now let's analyze the viral and fungal profiling results from Sylph."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Analyze viral results if available\n",
    "viruses_file = processed_data_dir / 'sylph_viruses_abundance.csv'\n",
    "if viruses_file.exists():\n",
    "    viruses_df = pd.read_csv(viruses_file, index_col=0)\n",
    "    \n",
    "    print(f\"Viral abundance table contains {len(viruses_df.index)} viruses across {len(viruses_df.columns)} samples\")\n",
    "    \n",
    "    # Get most abundant viruses\n",
    "    top_viruses = viruses_df.mean(axis=1).sort_values(ascending=False).head(10)\n",
    "    print(\"\\nTop 10 most abundant viruses:\")\n",
    "    display(pd.DataFrame({'Mean Abundance (%)': top_viruses}))\n",
    "    \n",
    "    # Create a heatmap of top viruses\n",
    "    top_virus_indices = top_viruses.index\n",
    "    \n",
    "    if len(top_virus_indices) > 0:\n",
    "        plt.figure(figsize=(14, 8))\n",
    "        sns.heatmap(viruses_df.loc[top_virus_indices], cmap='viridis', \n",
    "                   yticklabels=True, xticklabels=True)\n",
    "        plt.title('Abundance of Top 10 Viruses Across Samples')\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "    \n",
    "    # Analyze viral diversity with metadata if available\n",
    "    metadata_file = project_root / 'metadata.csv'\n",
    "    if metadata_file.exists():\n",
    "        metadata_df = pd.read_csv(metadata_file)\n",
    "        metadata_df.set_index('SampleID', inplace=True)\n",
    "        \n",
    "        common_samples = list(set(viruses_df.columns).intersection(set(metadata_df.index)))\n",
    "        if common_samples and len(common_samples) >= 3:  # Need at least a few samples for analysis\n",
    "            # Check viral presence by timing\n",
    "            if 'Timing' in metadata_df.columns:\n",
    "                # For each timing, calculate percentage of samples with each virus\n",
    "                timing_presence = {}\n",
    "                \n",
    "                for timing, group in metadata_df.loc[common_samples].groupby('Timing'):\n",
    "                    timing_samples = group.index.tolist()\n",
    "                    \n",
    "                    # Calculate presence (>0 abundance) for each virus\n",
    "                    presence = (viruses_df[timing_samples] > 0).mean(axis=1) * 100\n",
    "                    timing_presence[timing] = presence\n",
    "                \n",
    "                # Create dataframe for visualization\n",
    "                presence_df = pd.DataFrame(timing_presence)\n",
    "                \n",
    "                # Get top viruses by maximum presence in any timing\n",
    "                presence_df['max'] = presence_df.max(axis=1)\n",
    "                top_present_viruses = presence_df.nlargest(10, 'max').index\n",
    "                \n",
    "                # Create heatmap of presence\n",
    "                plt.figure(figsize=(10, 8))\n",
    "                sns.heatmap(presence_df.loc[top_present_viruses].drop('max', axis=1), \n",
    "                           annot=True, cmap='viridis', fmt='.1f')\n",
    "                plt.title('Percentage of Samples with Virus Present by Timing')\n",
    "                plt.tight_layout()\n",
    "                plt.show()\n",
    "                \n",
    "                # Create bar chart of presence\n",
    "                presence_df.loc[top_present_viruses].drop('max', axis=1).plot(kind='bar', figsize=(12, 6))\n",
    "                plt.title('Percentage of Samples with Virus Present by Timing')\n",
    "                plt.ylabel('Presence (%)')\n",
    "                plt.legend(title='Timing')\n",
    "                plt.tight_layout()\n",
    "                plt.show()\n",
    "        else:\n",
    "            print(\"Insufficient common samples between viral data and metadata\")\n",
    "    else:\n",
    "        print(\"Metadata file not found\")\n",
    "else:\n",
    "    print(\"Viral abundance file not found\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Analyze fungal results if available\n",
    "fungi_file = processed_data_dir / 'sylph_fungi_abundance.csv'\n",
    "if fungi_file.exists():\n",
    "    fungi_df = pd.read_csv(fungi_file, index_col=0)\n",
    "    \n",
    "    print(f\"Fungal abundance table contains {len(fungi_df.index)} fungi across {len(fungi_df.columns)} samples\")\n",
    "    \n",
    "    # Get most abundant fungi\n",
    "    top_fungi = fungi_df.mean(axis=1).sort_values(ascending=False).head(10)\n",
    "    print(\"\\nTop 10 most abundant fungi:\")\n",
    "    display(pd.DataFrame({'Mean Abundance (%)': top_fungi}))\n",
    "    \n",
    "    # Create a heatmap of top fungi\n",
    "    top_fungi_indices = top_fungi.index\n",
    "    \n",
    "    if len(top_fungi_indices) > 0:\n",
    "        plt.figure(figsize=(14, 8))\n",
    "        sns.heatmap(fungi_df.loc[top_fungi_indices], cmap='viridis', \n",
    "                   yticklabels=True, xticklabels=True)\n",
    "        plt.title('Abundance of Top 10 Fungi Across Samples')\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "    \n",
    "    # Similar analysis as for viruses but with fungi\n",
    "    # ...\n",
    "else:\n",
    "    print(\"Fungal abundance file not found\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Integrated Analysis Across Microbial Kingdoms\n",
    "\n",
    "Finally, let's perform an integrated analysis across bacterial, viral, and fungal communities."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Load the combined microbial table\n",
    "all_microbes_file = processed_data_dir / 'sylph_all_microbes_abundance.csv'\n",
    "if all_microbes_file.exists():\n",
    "    all_microbes_df = pd.read_csv(all_microbes_file, index_col=0)\n",
    "    \n",
    "    print(f\"Combined microbial table contains {len(all_microbes_df.index)} taxa across {len(all_microbes_df.columns)} samples\")\n",
    "    \n",
    "    # Extract kingdom information from the index\n",
    "    kingdoms = []\n",
    "    for taxon in all_microbes_df.index:\n",
    "        if taxon.startswith('Bacteria:'):\n",
    "            kingdoms.append('Bacteria')\n",
    "        elif taxon.startswith('Virus:'):\n",
    "            kingdoms.append('Virus')\n",
    "        elif taxon.startswith('Fungus:'):\n",
    "            kingdoms.append('Fungus')\n",
    "        else:\n",
    "            kingdoms.append('Unknown')\n",
    "    \n",
    "    # Add kingdom information\n",
    "    kingdom_df = pd.DataFrame({'Kingdom': kingdoms}, index=all_microbes_df.index)\n",
    "    \n",
    "    # Calculate mean abundance by kingdom\n",
    "    kingdom_abundance = pd.DataFrame({\n",
    "        'Mean Abundance': all_microbes_df.mean(axis=1),\n",
    "        'Kingdom': kingdom_df['Kingdom']\n",
    "    })\n",
    "    \n",
    "    kingdom_summary = kingdom_abundance.groupby('Kingdom')['Mean Abundance'].agg(['sum', 'count'])\n",
    "    kingdom_summary.columns = ['Total Abundance (%)', 'Number of Taxa']\n",
    "    \n",
    "    print(\"\\nKingdom summary:\")\n",
    "    display(kingdom_summary)\n",
    "    \n",
    "    # Create pie chart of kingdom abundances\n",
    "    plt.figure(figsize=(10, 7))\n",
    "    plt.pie(kingdom_summary['Total Abundance (%)'], labels=kingdom_summary.index, \n",
    "           autopct='%1.1f%%', startangle=90)\n",
    "    plt.title('Relative Abundance by Microbial Kingdom')\n",
    "    plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle\n",
    "    plt.show()\n",
    "    \n",
    "    # Load metadata for integrated analysis\n",
    "    metadata_file = project_root / 'metadata.csv'\n",
    "    if metadata_file.exists():\n",
    "        metadata_df = pd.read_csv(metadata_file)\n",
    "        metadata_df.set_index('SampleID', inplace=True)\n",
    "        \n",
    "        common_samples = list(set(all_microbes_df.columns).intersection(set(metadata_df.index)))\n",
    "        if common_samples:\n",
    "            # Calculate kingdom ratio by sample\n",
    "            kingdom_ratios = pd.DataFrame(index=common_samples, columns=['Bacteria', 'Virus', 'Fungus', 'Unknown'])\n",
    "            \n",
    "            for sample in common_samples:\n",
    "                sample_abundances = all_microbes_df[sample]\n",
    "                \n",
    "                # Calculate sum by kingdom\n",
    "                for kingdom in ['Bacteria', 'Virus', 'Fungus', 'Unknown']:\n",
    "                    kingdom_indices = [i for i, k in enumerate(kingdoms) if k == kingdom]\n",
    "                    if kingdom_indices:\n",
    "                        kingdom_sum = sample_abundances.iloc[kingdom_indices].sum()\n",
    "                        kingdom_ratios.loc[sample, kingdom] = kingdom_sum\n",
    "                    else:\n",
    "                        kingdom_ratios.loc[sample, kingdom] = 0\n",
    "            \n",
    "            # Join with metadata\n",
    "            for col in ['Timing', 'Symptoms', 'Severity']:\n",
    "                if col in metadata_df.columns:\n",
    "                    kingdom_ratios[col] = metadata_df.loc[common_samples, col].values\n",
    "            \n",
    "            # Analyze kingdom ratio by timing\n",
    "            if 'Timing' in kingdom_ratios.columns:\n",
    "                # Calculate mean ratio by timing\n",
    "                timing_means = kingdom_ratios.groupby('Timing')[['Bacteria', 'Virus', 'Fungus']].mean()\n",
    "                \n",
    "                # Create stacked bar chart\n",
    "                ax = timing_means.plot(kind='bar', stacked=True, figsize=(10, 6))\n",
    "                ax.set_ylabel('Mean Abundance (%)')\n",
    "                ax.set_title('Mean Abundance of Microbial Kingdoms by Timing')\n",
    "                ax.legend(title='Kingdom')\n",
    "                plt.tight_layout()\n",
    "                plt.show()\n",
    "            \n",
    "            # Analyze kingdom ratio by symptoms\n",
    "            if 'Symptoms' in kingdom_ratios.columns:\n",
    "                # Calculate mean ratio by symptoms\n",
    "                symptom_means = kingdom_ratios.groupby('Symptoms')[['Bacteria', 'Virus', 'Fungus']].mean()\n",
    "                \n",
    "                # Create stacked bar chart\n",
    "                ax = symptom_means.plot(kind='bar', stacked=True, figsize=(10, 6))\n",
    "                ax.set_ylabel('Mean Abundance (%)')\n",
    "                ax.set_title('Mean Abundance of Microbial Kingdoms by Symptoms')\n",
    "                ax.legend(title='Kingdom')\n",
    "                plt.tight_layout()\n",
    "                plt.show()\n",
    "                \n",
    "                # Create boxplots of bacteria-to-virus ratio\n",
    "                kingdom_ratios['{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Sylph Microbiome Analysis\n",
    "\n",
    "This notebook demonstrates how to process, analyze, and visualize Sylph microbiome profiling outputs for the RSV microbiome project.\n",
    "\n",
    "## Analysis steps:\n",
    "1. Parse Sylph output files\n",
    "2. Create abundance tables\n",
    "3. Compare results with MetaPhlAn\n",
    "4. Analyze bacterial, viral, and fungal profiles\n",
    "5. Integrate with metadata for RSV analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Import necessary libraries\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import re\n",
    "from pathlib import Path\n",
    "import subprocess\n",
    "from scipy.stats import spearmanr, pearsonr\n",
    "\n",
    "# Set plotting style\n",
    "sns.set(style=\"whitegrid\")\n",
    "plt.rcParams['figure.figsize'] = (12, 8)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Setup paths and import processing script\n",
    "\n",
    "First, we'll set up the paths to our data and import the Sylph processing script that we've created."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Set up paths\n",
    "project_root = Path.cwd().parent\n",
    "sylph_profile_dir = project_root / 'SylphProfiles'  # Location of Sylph outputs\n",
    "processed_data_dir = project_root / 'data' / 'processed'  # Where processed files will go\n",
    "results_dir = project_root / 'results'\n",
    "comparison_dir = results_dir / 'sylph_metaphlan_comparison'\n",
    "\n",
    "# Create directories if they don't exist\n",
    "processed_data_dir.mkdir(exist_ok=True, parents=True)\n",
    "comparison_dir.mkdir(exist_ok=True, parents=True)\n",
    "\n",
    "# Path to the scripts\n",
    "sylph_process_script = project_root / 'scripts' / 'process_sylph_outputs.py'\n",
    "comparison_script = project_root / 'scripts' / 'compare_sylph_metaphlan.py'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Run the Sylph processing script\n",
    "\n",
    "Now, we'll run the `process_sylph_outputs.py` script that we created to process the Sylph output files."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Save the script to a file if it doesn't exist yet\n",
    "if not sylph_process_script.exists():\n",
    "    # Copy the script content here\n",
    "    script_content = \"\"\"#!/usr/bin/env python3\n",
    "\"\"\"Parse and process Sylph output files for microbiome analysis.\"\"\"\n",
    "# ... (full script content from previously created artifact)\n",
    "\"\"\"\n",
    "    \n",
    "    with open(sylph_process_script, 'w') as f:\n",
    "        f.write(script_content)\n",
    "    \n",
    "    # Make it executable\n",
    "    os.chmod(sylph_process_script, 0o755)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Run the processing script\n",
    "cmd = [\n",
    "    'python', str(sylph_process_script),\n",
    "    '--input-dir', str(sylph_profile_dir),\n",
    "    '--output-dir', str(processed_data_dir),\n",
    "    '--metadata', str(project_root / 'metadata.csv'),\n",
    "    '--min-ani', '90',  # Lower threshold to include more matches\n",
    "    '--min-coverage', '0.01'  # Lower threshold for coverage\n",
    "]\n",
    "\n",
    "# Execute the command and capture output\n",
    "process = subprocess.run(cmd, capture_output=True, text=True)\n",
    "\n",
    "# Print the output\n",
    "print(process.stdout)\n",
    "if process.stderr:\n",
    "    print(\"Errors:\")\n",
    "    print(process.stderr)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Explore the processed Sylph data\n",
    "\n",
    "Now that we've processed the Sylph outputs, let's explore the resulting abundance tables."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Load the bacterial abundance table\n",
    "bacteria_file = processed_data_dir / 'sylph_bacteria_abundance.csv'\n",
    "\n",
    "if bacteria_file.exists():\n",
    "    bacteria_df = pd.read_csv(bacteria_file, index_col=0)\n",
    "    print(f\"Loaded bacterial abundance table with {len(bacteria_df.index)} species across {len(bacteria_df.columns)} samples\")\n",
    "    print(\"\\nTop 10 most abundant bacteria:\")\n",
    "    top_bacteria = bacteria_df.mean(axis=1).sort_values(ascending=False).head(10)\n",
    "    display(pd.DataFrame({'Mean Abundance (%)': top_bacteria}))\n",
    "else:\n",
    "    print(\"Bacterial abundance file not found. Please ensure the processing script ran successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Check other microbial types\n",
    "file_types = {\n",
    "    'Viruses': processed_data_dir / 'sylph_viruses_abundance.csv',\n",
    "    'Fungi': processed_data_dir / 'sylph_fungi_abundance.csv',\n",
    "    'All microbes': processed_data_dir / 'sylph_all_microbes_abundance.csv'\n",
    "}\n",
    "\n",
    "for label, file_path in file_types.items():\n",
    "    if file_path.exists():\n",
    "        df = pd.read_csv(file_path, index_col=0)\n",
    "        print(f\"\\n{label}: Found {len(df.index)} taxa across {len(df.columns)} samples\")\n",
    "        \n",
    "        if not df.empty:\n",
    "            print(f\"Top 5 most abundant {label.lower()}:\")\n",
    "            top = df.mean(axis=1).sort_values(ascending=False).head(5)\n",
    "            display(pd.DataFrame({'Mean Abundance (%)': top}))\n",
    "    else:\n",
    "        print(f\"\\n{label}: File not found\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Visualize bacterial composition\n",
    "\n",
    "Let's create some visualizations of the bacterial composition."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Only proceed if we have bacterial data\n",
    "if bacteria_file.exists():\n",
    "    bacteria_df = pd.read_csv(bacteria_file,